Feature/user friendly
alchemycodelab/computer-setup-script pull request #5
Opened 2021-09-16 18:21 UTC by sarah-svg

Let me know if I need to change or update anything!
 **NEW** I separated the mac and linux brew file the old one is still there can delete if you like the changes. Made sure the markdown file had nice whitespace between each entry. Made Mac Users  and Linux Users separate. Fixed the spelling error. Also took off the link for nvm can remove  file if you like this setup better..

2021-09-16 18:31 UTC, martypdx requested changes
Few things to address:

1. Change links to link the relevant text
2. Please check for consistent whitespace in markdown formatting
3. Let's organize the main page **by OS**. So have separate "Mac", "Windows", and "Linux" sections that have the list of linked items to go do for that OS
4. Decide on nvm vs node install for Mac and Linux

2021-09-16 18:31 UTC, martypdx commented on README.md
> + * [Link](git-for-windows-instal.md)
Instead of the word "Link", let's link the task:

```md
1. [Install git for Windows](git-for-windows-instal.md)
```

2021-09-16 18:31 UTC, martypdx commented on brew-mac-linux.md
> +* Go to homebrew and instal [Link](https://brew.sh/)
missing "L": instal**l**

2021-09-16 18:31 UTC, martypdx commented on node-for-mac-linux.md
> +### Install Node
If we aren't doing `nvm`, then "Install Node" is same for all OS, right?

2021-09-16 18:33 UTC, sarah-svg commented on node-for-mac-linux.md
> +### Install Node
yes it would be.

2021-09-16 18:47 UTC, sarah-svg commented on brew-mac-linux.md
> +* Go to homebrew and instal [Link](https://brew.sh/)
Fixed this thanks!!

2021-09-16 18:49 UTC, sarah-svg commented on node-for-mac-linux.md
> +### Install Node
Does this mean I can just take out the nvm section on the readme?

2021-09-20 17:15 UTC, martypdx requested changes

2021-09-20 17:15 UTC, martypdx commented on vscode-windows.md
> +5. Go back to [here](vscode-all.md) for validation step.
@sarah-svg we don't need this file

2021-09-20 17:15 UTC, martypdx commented on README.md
> +        [ `Windows` after vscode install](vscode-windows.md)
We don't need to do this, it's for WSL (Linux on Windows). We are doing straight Windows

2021-09-20 17:15 UTC, martypdx commented on README.md
> +  3. [Install `Homebrew` for Mac](brew-mac.md)
Homebrew needs to happen before Git, because Git step is using homebrew to install

2021-09-20 17:15 UTC, martypdx commented on node-for-mac-linux.md
> + You should see some numbers like so: `v14.0.0`. The exact numbers will probably be different, but as long as you're getting numbers, you can count this as a success!
We don't need this file, all node installs are the same

2021-09-20 17:15 UTC, martypdx commented on node-window-users.md
> +#Windows Users Node Install
Make this "Node Install" (and change file name). It's the same for all users

2021-09-20 17:15 UTC, martypdx commented on node-window-users.md
> +After using the Windows installer in the above link, open a new GitBash terminal and run the following command:
```md
After completing the node install, open a new terminal and run the following command:
```

2021-09-20 17:15 UTC, martypdx commented on git-mac-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
This is confusing, do we need it?

2021-09-20 17:15 UTC, martypdx commented on git-linux-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
Confusing, do we need this?

2021-09-20 20:22 UTC, sarah-svg commented on all-user-git-config.md
> +```
okay took that out of this file.

2021-09-20 20:23 UTC, sarah-svg commented on brew-linux.md
> +* Open up Terminal Ubuntu App (Windows)
ok made a brew-instal file for both linux and mac together not separated now.

2021-09-20 20:24 UTC, sarah-svg commented on brew-mac-linux.md
> +
ok just have one brew file currently for both os.

2021-09-20 20:24 UTC, sarah-svg commented on git-for-windows-instal.md
> +Look closely at the first two filenames in the list. One says "32 bit", and the other says "64 bit". Those are the different versions for 32-bit and 64-bit Windows. Download the one for your system.
took that paragraph out

2021-09-20 20:26 UTC, sarah-svg commented on vscode-windows.md
> +5. Go back to [here](vscode-all.md) for validation step.
ok deleted this file and linked it to vscode-all for all os.

2021-09-20 20:26 UTC, sarah-svg commented on README.md
> +        [ `Windows` after vscode install](vscode-windows.md)
took out that extra step since we dont need it

2021-09-20 20:28 UTC, sarah-svg commented on README.md
> +  3. [Install `Homebrew` for Mac](brew-mac.md)
Moved homebrew to the first step for linux and the second step for mac right after the xcode install

2021-09-20 20:31 UTC, sarah-svg commented on node-for-mac-linux.md
> + You should see some numbers like so: `v14.0.0`. The exact numbers will probably be different, but as long as you're getting numbers, you can count this as a success!
ok now the links for node install go to the same file for all os , renamed it to install-node

2021-09-20 20:31 UTC, sarah-svg commented on node-window-users.md
> +After using the Windows installer in the above link, open a new GitBash terminal and run the following command:
added this sentence to instal node file

2021-09-20 20:32 UTC, sarah-svg commented on git-linux-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
Took that out

2021-09-20 20:32 UTC, sarah-svg commented on git-mac-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
took it out.

2021-09-20 20:33 UTC, sarah-svg commented on node-window-users.md
> +#Windows Users Node Install
ok done!

2021-09-20 23:06 UTC, sarah-svg commented on all-user-git-config.md
> +```
took this out also

2021-09-20 23:07 UTC, sarah-svg commented on brew-mac.md
> +
Made one file called brew-install for all os that need to have brew installed

2021-09-20 23:07 UTC, sarah-svg commented on git-for-windows-instal.md
> +Look closely at the first two filenames in the list. One says "32 bit", and the other says "64 bit". Those are the different versions for 32-bit and 64-bit Windows. Download the one for your system.
took this out completely

2021-09-20 23:08 UTC, sarah-svg commented on vscode-windows.md
> +5. Go back to [here](vscode-all.md) for validation step.
deleted the link to this fila and the file itself

2021-09-20 23:09 UTC, sarah-svg commented on README.md
> +        [ `Windows` after vscode install](vscode-windows.md)
took out the link and file pertaining to this message .

2021-09-20 23:09 UTC, sarah-svg commented on README.md
> +  3. [Install `Homebrew` for Mac](brew-mac.md)
Move homebrew as the fist step for linux and the second step for mac after xcode

2021-09-20 23:11 UTC, sarah-svg commented on node-for-mac-linux.md
> + You should see some numbers like so: `v14.0.0`. The exact numbers will probably be different, but as long as you're getting numbers, you can count this as a success!
renamed file to install-node for all os and have the links changed to reflect that file instead

2021-09-20 23:14 UTC, sarah-svg commented on node-window-users.md
> +After using the Windows installer in the above link, open a new GitBash terminal and run the following command:
Added this sentence to the file install-node file for all os

2021-09-20 23:14 UTC, sarah-svg commented on git-mac-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
took it out

2021-09-20 23:14 UTC, sarah-svg commented on git-linux-users.md
> +* Go back to the read me and follow the link for step 2 [Readme Link](README.md)
took out also

2021-09-21 22:56 UTC, martypdx approved these changes

2021-09-21 22:56 UTC, merged